name: Run in Renode
description: Runs a specified sample in Renode
inputs:
  proj-name:
    description: Name of the project
    required: true
  platform:
    description: Platform used to build sample
    required: true
  test:
    description: Path to the test file
    required: true
  build-params:
    description: Additional build parameters
    required: false
    default: ''

runs:
  using: "includes"
  steps:
    - name: Fetch toolchain
      run: |
        wget -O- https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz | tar -xzC /opt
        echo "/opt/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin" >> $GITHUB_PATH

    - name: Clone repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Setup environment
      run: bash scripts/setup -ci

    - name: Build sample & generate Renode scripts
      run:
        pwd && source environment && cd proj/${{ inputs.proj-name }} &&
        make ${{ inputs.build-params }} PLATFORM=${{ inputs.platform }} TARGET=${{ matrix.target }} -j8 software &&
        make renode-scripts TARGET=${{ matrix.target }}

    - name: Run tests
      timeout-minutes: 5
      uses: antmicro/renode-actions/test-in-renode@main
      with:
        renode-version: '1.12.0+20210403git44d6786'
        tests-to-run: ${{ inputs.test }}

    - name: Archive results
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{ inputs.proj-name }}-${{ inputs.platform }}-${{ matrix.target }}
        path: |
          report.html
          log.html
          robot_output.xml
          snapshots
